### PR TITLE
Tool calling

### PR DESCRIPTION
**Pull request by pcuenca**
In progress. My idea is to cover:

- [x] Built-in tools. Use just `tokenizer.apply_chat_template` to explain how the process works, and actually use one of the built-in tools (Brave search) using the reference implementation from https://github.com/meta-llama/llama-stack/blob/f2e18826b6f9c0122eb714f3bda404da19d2355b/llama_toolchain/agentic_system/meta_reference/tools/builtin.py#L88.
- [ ] Custom tools.
- [ ] Unified API based on https://huggingface.co/blog/unified-tool-use

It could also be separate notebooks if preferred.

### CODE REVIEW

**Comment by sergiopaniego** [comment]
Hi @pcuenca!
Are you still working on it? I would like to help if you’re short on time.

**Comment by sergiopaniego** [comment]
I’ve been diving into this topic and learning a lot along the way! 😄

I’ve extended the notebook in this [Colab](https://colab.research.google.com/drive/1m6Khs50iuzlJ5o-3w56jTHrUdsTNmRkK) and if you're interested in collaborating, feel free to check it out. It's fully functional but could use more detailed explanations and definitely has lots of room for improvement. Let me know if this aligns with what you had in mind!

**Comment by pcuenca** [comment]
Hello @sergiopaniego! From a quick look, I like the approach you followed, building up progressively to show how things work. I put my notebook on pause waiting for Llama 3.2, and both @ariG23498 and myself have done some testing with the new version. I think this is work that complements what you did, but there are a few differences with respect to 3.1: built-in tools are no longer encouraged, and custom tools seem to favor a slightly different format, [whose details are not yet fully clear to me](https://github.com/meta-llama/llama-stack-apps/issues/36#issuecomment-2402889379) after debugging the llama-stack library. We found that tool calling with the small 3.2 models tends to be fragile, and therefore getting the prompt details right is crucial. Our goal is to clarify the recommended prompt format, create a chat template for these models that follows it, and then document how (or if) the 3.2 models work with tool calling. My understanding is that this prompt format should also be compatible with the 3.1 models (including the 3.1 language towers that are part of the 3.2 VLMs). If that's the case then it'd make things easier as we could use a similar chat template for all the models.

In my opinion, a notebook that focuses mostly on 3.2 but also discusses how things work with the larger 3.1 models would be great. Perhaps the three of us can collaborate on this, assuming we get the details for the 3.2 models right. What do you think @ariG23498 @sergiopaniego?

**Comment by sergiopaniego** [comment]
Thank you for the detailed explanation, @pcuenca. I’m also running into some confusion while building the pipeline. I agree that creating a notebook focused on the latest version, while also discussing the 3.1 workflow, could be really helpful.

What do you think would be the best way to iterate on this @pcuenca @ariG23498?

**Comment by pcuenca** [comment]
Superseded by #84

**Pull request closed without merging**
