### PR TITLE
Issue #47 Adding a simple LLaMa-RAG pipeline

### PR DESCRIPTION
**Pull request by Solobrad**
### Summary

Issue #47: "Call for Contributions #43: LLMs and RAG ." 

### Changes Made

- Developed a straightforward pipeline using LLaMa and RAG (ChromaDB).
- Implemented functionality to load documents from local file paths (PDFs)

### CODE REVIEW

**Comment by ariG23498** [comment]
While this is a very thorough example I have the following suggestions:
1. Use a dataset from the Hugging Face Hub
2. Use [Sentence Transformers](https://sbert.net/) to embed the dataset & retrieve the text
3. Take a look at RAG in [chat template](https://huggingface.co/docs/transformers/en/chat_templating#advanced-retrieval-augmented-generation) and try using that for Llama (this is experimental, if this does not work, please feel free to inject the retrieved text in the prompt manually)


My suggestions are based on the following ideas:
1. Keeping everything Hugging Face oriented -- and not using third part applications
2. Keeping it simple
3. Also letting the reader use the dataset, and see how to tweak the code with minimal efforts

What do you think about the suggestions?

**Comment by Solobrad** [comment]
Awesome, will work on it ASAP.

**Comment by sinatayebati** [comment]
@Solobrad Hi Nicholas, 
as @ariG23498 suggested I built upon your work and opened a PR on your branch suggesting some improvements in your notebook. Let me know your thoughts.

**Comment by Solobrad** [comment]
@sinatayebati Thanks for the thorough modifications, I really appreciate it! Would it be alright if I added you to my repo as a collaborator so we can work together on any future changes?

**Comment by sinatayebati** [comment]
@Solobrad absolutely! please feel free to add me, I'd be more than happy to contribute.

**Comment by ariG23498** [comment]
Hey folks! I love how thorough this is, but I feel we need a simple demo and not end to end (like the one you all have proposed)

Here are what I thought:
- Have a dictionary snippets of text that can be looked up
- Use the Sentence Transformer library to embed the snippets in the dictionary
- Use Sentence Transformers to retrieve a text from the dictionary using cosine similarity
- Add that text into the prompt with `f-string`
- Generate the new prompt

The idea is for people to understand what a **very simple** RAG pipeline looks like. I would steer away from using any 3rd party libraries that are used for more complicated RAG pipelines.

Please let me know what you all think!

**Comment by Solobrad** [comment]
Your message is well phrased! Here's a slight refinement to ensure clarity:

Hi @ariG23498,

Just to confirm, we no longer need LLaMA, right? If that's the case, we're focusing on a DEMO with RAG and not LLaMA-RAG as previously mentioned.

**Comment by Solobrad** [comment]
Hi @ariG23498,

Just to confirm, we no longer need LLaMA, right? If that's the case, we're focusing on a DEMO with RAG and not LLaMA-RAG as previously mentioned.

**Comment by sinatayebati** [comment]
@Solobrad Hey Nicholas, thanks for the latest commits. My understanding of Aritra's feedback is that we still need `Llama` in the pipeline (otherwise it does't really make sense to me), but I believe he wanted to remove the need for a dedicated vector store and Langchain integration.

I believe what you pushed lately is very close, but let's see what's @ariG23498 feedback is, and we take it from there.

**Comment by Solobrad** [comment]
@sinatayebati, ya I know right because my Issue was initially "LLaMa-RAG". But that "not end to end" part made me rethink about it. Oh, I've mentioned you in one of the issues we are working on, did you see it?

**Comment by sinatayebati** [comment]
@Solobrad yes I noticed that. will be happy to contribute and help the team. let's see what feedback we get from HF team and we take it from there.

**Comment by sinatayebati** [comment]
@ariG23498 Hi Aritra,

We've implemented the updates you suggested. The [notebook](https://github.com/Solobrad/huggingface-llama-recipes/blob/llama-rag/llama_rag/llama_rag_pipeline.ipynb) now presents a minimal example of a basic Llama RAG experiment. 

We'd appreciate your thoughts on any further refinements, and we're eager to know if you think this branch is ready for merging.

**Comment by ariG23498** [comment]
We are really close to getting this merged! Really like how simple the notebook is.

Here is my [notebook](https://colab.research.google.com/gist/ariG23498/7dc2b97839cd78b34bcc5a0333e44e51/scratchpad.ipynb) based on your example, to note:
1. We do not need the `dotenv` as colab already takes care of login
2. I have used `pipeline`
3. Also the retrieval code is simpler now

If you all can incorporate these changes, I will be happy to merge this PR.

Also, try adding markdown and a short description about the code in the code cells -- so that a beginner would understand what is happening at each code cell.

**Review by ariG23498 — APPROVED** [review]
Really close to merge.

Two nits:
1. Remove the last cell from the notebook
2. Swap `%pip install -Uq sentence-transformers` with `!pip install -Uq sentence-transformers`

Thanks for making this happen, looks really nice!

**Comment by sinatayebati** [comment]
@ariG23498 Hi Ari, thanks for your feedback. 

According to your comments, @Solobrad made the latest changes and I made some touch ups (removing last cell, updating the pip install and resolve a small conflict). We should be all good now, the PR is clean and I see no conflicts with the upstream 🚀

**Comment by ariG23498** [comment]
Thanks for the great contribution folks!

**Pull request merged**
