### PR TITLE
Tool calling recipe

### PR DESCRIPTION
**Pull request by sergiopaniego**
Work in progress.

Collaborative PR involving: @pcuenca, @ariG23498, @sergiopaniego.

This PR builds upon the efforts outlined in #29.

### CODE REVIEW

**Review by Vaibhavs10 — COMMENTED** [review]
Thanks for opening the PR @sergiopaniego 🤗

Some light feedback before we get started:
1. On first impressions - let's add information about what is happening in each step/ cell. It's good to assume that people don't understand the code and explain what are you doing in each cell.
2. People would need to accept and authenticate to the hugging face hub before loading the model so it'd be good to add a disclaimer to accept the license and then follow it up a call to HF Hub python lib to authenticate.

Very cool notebook and love the simplicity. By adding more detailed information in between cells it'd make it significantly more impactful.

**Comment by sergiopaniego** [comment]
My bad @Vaibhavs10, forgot to add that the PR is still a work in progress and not ready to be reviewed 😅

I will include this feedback! ☺️

**Comment by ariG23498** [comment]
@sergiopaniego the notebook is going to be one of the best ones in the repository. Thank you for all the hard work.

Only a single nit -- The image in the beginning has a transparent background (I assume) which is a problem with dark GitHub theme. For me it looks something like this 👇 
image
Once we have this fixed I would be happy to merge.

@Vaibhavs10 @pcuenca would you all like to skim through as well?

**Review by Vaibhavs10 — COMMENTED** [review]
Very cool @sergiopaniego 🔥 

>For deployment options, you may want to consider [llama-stack-apps](https://github.com/meta-llama/llama-stack-apps) and [llama-stack](https://github.com/meta-llama/llama-stack).

Perhaps we can link TGI and INference endpoints here as well (we can also link the corresponding tutorials)

Smol nit: I'd add a link to where people can get their corresponding HF access tokens: https://huggingface.co/settings/tokens

I'd move the installation of `llama-stack` to down below, and show snippets to install `transformers` + `huggingface_hub` in the first block.

Suggestion to split Unit 3 onward in a separate notebook, this way both the notebooks won't too long and text/ output heavy.

Is there no other way to use BraveSearch except via llama stack? AFAICT it;s the only reason for importing LlamaStack right?

**Comment by sergiopaniego** [comment]
Thanks for the feedback, @ariG23498 and @Vaibhavs10!  🤗 

I've updated the notebook accordingly:  
- Updated the diagram with a white background (@ariG23498).  
- Added details about TGI and Inference Endpoints, along with their tutorials (@Vaibhavs10).  
- Added a link to guide users on obtaining their Hugging Face access token.  
- Moved the `llama-stack` installation further down and added installation instructions for `transformers` and `huggingface_hub`.

Regarding the last two comments (@Vaibhavs10):  
- I’m okay with splitting it into two separate notebooks. Since @ariG23498 and @pcuenca have also contributed, I’d like to hear their thoughts first. 😄  
- You're correct that we only use `llama-stack` to import `BraveSearch` ([reference](https://github.com/meta-llama/llama-stack/blob/b1a63df8cdae6e45d1db10f8c73eca6cd75ba68e/llama_stack/providers/inline/agents/meta_reference/tools/builtin.py#L153)). The reason for this choice is simplicity, as it searches and returns the parsed output we need. I tried using `DuckDuckGoSearchTool` from `transformers` ([reference](https://github.com/huggingface/transformers/blob/4120cb257f03b834fb332e0b0ee6570245e85656/src/transformers/agents/search.py#L25)), but it doesn’t directly produce the required output, so additional steps would be needed.

**Comment by ariG23498** [comment]
I am okay with splitting the notebook 🤗

**Comment by pcuenca** [comment]
Great work! I opened a PR with a few minor nits, please feel free to ignore the ones you don't agree with: https://github.com/sergiopaniego/huggingface-llama-recipes/pull/1

Regarding the bos token, I think the problem is that calling the tokenizer will add a `bos` token by default. Some tokenizers do this while others don't, so the criteria used by chat templates is to include everything that's needed, in order to avoid any ambiguity.

If we call the tokenizer using `add_special_tokens=False`, we should be able to use the chat template with the bos and it should work.

Not sure if it'd be helpful or more confusing, but showing a couple of tokenized examples (with the IDs) might be interesting. What really matters is the numerical IDs, telling people to look at them to make sure everything's right is not a bad advice in my opinion. But it may become difficult to integrate, so your call!

**Comment by pcuenca** [comment]
Regarding splitting it up, I like that it's comprehensive. Everything is essentially covered in the first example, perhaps we could just tell the reader that that's it (we have a working chat template at that point), and invite them to go through the more complicated example if they are interested.

**Comment by sergiopaniego** [comment]
Thanks so much for your comments, @ariG23498 and @pcuenca! 🤗

The issue I previously mentioned regarding strange outputs was caused by setting `add_special_tokens=True`. It's all working smoothly now! 😄 Apologies for the inconvenience, and thank you for your patience! 🙏

Here’s what I’ve done:

- Included @pcuenca's update.
- Added the `add_special_tokens` setting and set it to `False` when using the `chat_template`.
- Added a brief explanation about this change at the end of the addition example, right before moving on to the web search section.
- Included a note, referencing @pcuenca’s last message, explaining that the content has been thoroughly covered and that, from here on, we’ll present a more complex example for those who want a challenge.
- Kept everything as a single, standalone example, as suggested by @pcuenca.

I believe that's everything! 😄

**Review by pcuenca — APPROVED** [review]
Looks good for me to merge! Thanks a lot for your patience to iterate, @sergiopaniego, I think the result is amazing! 😍

**Comment by ariG23498** [comment]
Thank you @sergiopaniego!

**Pull request merged**
