### PR TITLE
Improve prompt guard tutorial (advanced section)

### PR DESCRIPTION
**Pull request by xenova**
Follow-up to #11.

### CODE REVIEW

**Review by osanseviero — APPROVED** [review]
LGTM! Quick feedback

* No need to reimport `AutoTokenizer` and `AutoModelForSequenceClassification`

**Comment by xenova** [comment]
I suppose I could just remove that block too 👍 (since I load the model above anyway). I had it there initially since it's across two sections (the basic and advanced, with each being standalone). WDYT?

**Review by pcuenca — APPROVED** [review]
Very cool! Loved the padding / reshape approach :)

**Comment by pcuenca** [comment]
> I suppose I could just remove that block too 👍 (since I load the model and tokenizer above anyway). I had it there initially since it's across two sections (the basic and advanced, with each being standalone). WDYT?

I thought the same about the two sections being standalone, I'd keep the imports so people can focus on what they are interested in. Your call!

**Pull request merged**
